export const CHANGE_ISLIKED_PROPERTY = "CHANGE_ISLIKED_PROPERTY";
export const CHANGE_PRODUCT_RATING = "CHANGE_PRODUCT_RATING";
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'
