const PRODUCTS = [
  {
    id: 1,
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    title: "Brown Brim",
    price: 50,
    tags: ["hats", "milf", "fuck milf"],
    isLiked: true,
    rating: 5,
    city: "Hong Kong",
  },
  {
    id: 2,
    imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    title: "Blue Beanie",
    price: 40,
    tags: ["condons", "hats", "fuck milf"],
    isLiked: false,
    rating: 5,
    city: "Hong Kong",
  },
  {
    id: 3,
    imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
    title: "Brown Cowboy",
    price: 45,
    tags: ["hats", "hats", "hats"],
    isLiked: false,
    rating: 5,
    city: "Hong Kong",
  },
  {
    id: 4,
    imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
    title: "Grey Brim",
    price: 30,
    tags: ["hats", "hats", "hats hats"],
    isLiked: false,
    rating: 5,
    city: "Hong Kong",
  },
  {
    id: 5,
    imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
    title: "Green Beanie",
    price: 60,
    tags: ["hats", "hats", "hats"],
    isLiked: false,
    rating: 5,
    city: "Hong Kong",
  },
  {
    id: 6,
    imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
    title: "Adidas NMD",
    price: 99,
    tags: ["sneakers", "sneakers", "sneakers"],
    isLiked: false,
    rating: 5,
    city: "Brooklyn",
  },
  {
    id: 7,
    imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
    title: "Adidas Yeezy",
    price: 90,
    tags: ["sneakers", "sneakers", "sneakers"],
    isLiked: false,
    rating: 5,
    city: "Brooklyn",
  },
  {
    id: 8,
    imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
    title: "Black Converse",
    price: 120,
    tags: ["sneakers", "sneakers", "sneakers"],
    isLiked: false,
    rating: 5,
    city: "Brooklyn",
  },
  {
    id: 9,
    imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
    title: "Nike White AirForce",
    price: 100,
    tags: ["sneakers", "sneakers", "sneakers"],
    isLiked: false,
    rating: 5,
    city: "Brooklyn",
  },
  {
    id: 10,
    imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
    title: "Timberlands",
    price: 102,
    tags: ["sneakers", "sneakers", "sneakers"],
    isLiked: false,
    rating: 5,
    city: "Brooklyn",
  },
  {
    id: 11,
    imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
    title: "Black Jean Shearling",
    price: 120,
    tags: ["jackets", "jackets", "jackets"],
    isLiked: false,
    rating: 5,
    city: "New York",
  },
  {
    id: 12,
    imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
    title: "Blue Jean Jacket",
    price: 130,
    tags: ["jackets", "jackets", "jackets"],
    isLiked: false,
    rating: 5,
    city: "New York",
  },
  {
    id: 13,
    imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    title: "Grey Jean Jacket",
    price: 110,
    tags: ["jackets", "jackets", "jackets"],
    isLiked: false,
    rating: 5,
    city: "New York",
  },
  {
    id: 14,
    imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
    title: "Brown Shearling",
    price: 99,
    tags: ["jackets", "jackets", "jackets"],
    isLiked: false,
    rating: 5,
    city: "New York",
  },
  {
    id: 15,
    imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    title: "Tan Trench",
    price: 135,
    tags: ["jackets", "jackets", "jackets"],
    isLiked: false,
    rating: 5,
    city: "New York",
  },
  {
    id: 16,
    imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
    title: "Blue Tanktop",
    price: 89,
    tags: ["candy", "candy", "candy candy"],
    isLiked: false,
    rating: 5,
    city: "Sydney",
  },
  {
    id: 17,
    imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
    title: "Floral Blouse",
    price: 80,
    tags: ["womens", "womens", "womens"],
    isLiked: false,
    rating: 5,
    city: "Sydney",
  },
  {
    id: 18,
    imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
    title: "Floral Dress",
    price: 65,
    tags: ["womens", "womens", "womens"],
    isLiked: false,
    rating: 5,
    city: "Sydney",
  },
  {
    id: 19,
    imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
    title: "Red Dots Dress",
    price: 70,
    tags: ["womens", "womens", "womens"],
    isLiked: false,
    rating: 5,
    city: "Sydney",
  },
  {
    id: 20,
    imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    title: "Striped Sweater",
    price: 75,
    tags: ["womens", "womens", "womens"],
    isLiked: false,
    rating: 5,
    city: "Sydney",
  },
];

export default PRODUCTS;
